
development:
  adapter: postgresql
  encoding: unicode
  database: hacker_news_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: hacker_news_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: hacker_news_production
  pool: 5
